steps:
  - name: gcr.io/cloud-builders/docker
    id: Build Image
    args: [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/cicd-basic:latest",
        "-f",
        "code/cicd_basic/Dockerfile", # Path to the Dockerfile
        "code/cicd_basic", # Build context
      ]

  - name: "gcr.io/$PROJECT_ID/cicd-basic:latest"
    id: Validation Test
    entrypoint: python
    args: ["-m", "unittest", "tests/test_calculate.py"]

  - name: gcr.io/cloud-builders/docker
    id: Push Image to GCR
    args: ["push", "gcr.io/$PROJECT_ID/cicd-basic:latest"]

options:
  logging: CLOUD_LOGGING_ONLY # or specify a logs bucket as needed
